# Generated by Django 5.2.6 on 2025-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='game_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
